name: publish

on:
  workflow_dispatch:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io

jobs:
  default:
    name: etcdkeeper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/docker/build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          # passthrough CI into build container
          context: .
          file: Dockerfile
          load: false
          tags: ramir-savvy/etcdkeeper:latest
          push: true
